### ISSUE TITLE
zhudi manual install then setup fails somehow

### ISSUE THREAD

**Issue by pyluyten** [Jiehong/Zhudi#2]
setup does prepare some files but crashes.

$ zhudi -s cfdict.u8 
Splitting dictionary in progress…
Traceback (most recent call last):
  File "/usr/bin/zhudi_gui.py", line 5, in <module>
    pkg_resources.run_script('zhudi==1.4', 'zhudi_gui.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 483, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1348, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/zhudi-1.4-py2.7.egg/EGG-INFO/scripts/zhudi_gui.py", line 43, in <module>

  File "/usr/lib/python2.7/site-packages/zhudi-1.4-py2.7.egg/EGG-INFO/scripts/zhudi_gui.py", line 30, in main

  File "build/bdist.linux-x86_64/egg/zhudi/**init**.py", line 74, in prepare_data
TypeError: **init**() takes at least 11 arguments (8 given)

below is only there if helpful.

or does it only leave incorrectly? if I run from the same directory (yes i did the awful way, everything in the same place ;)
$ ls
build  cfdict.u8  COPYING.tex  dist  doc  NEWS  pinyin  PKGBUILD  README.md  scripts  setup.py  simplified  tests.py  traditional  translation  zhudi  zhudi-data  zhudi.egg-info  zhudi.install

running zhudi will then fail
$  python /usr/bin/zhudi_gui.py -p pinyin -tr translation -sd simplified
No config file found. Use defaults
Traceback (most recent call last):
  File "/usr/bin/zhudi_gui.py", line 5, in <module>
    pkg_resources.run_script('zhudi==1.4', 'zhudi_gui.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 483, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1348, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/zhudi-1.4-py2.7.egg/EGG-INFO/scripts/zhudi_gui.py", line 43, in <module>

  File "/usr/lib/python2.7/site-packages/zhudi-1.4-py2.7.egg/EGG-INFO/scripts/zhudi_gui.py", line 30, in main

  File "build/bdist.linux-x86_64/egg/zhudi/**init**.py", line 143, in prepare_data
  File "build/bdist.linux-x86_64/egg/zhudi/chinese_table.py", line 56, in load
IOError: [Errno 2] 没有那个文件或目录: '/usr/share/zhudi-data/cangjie5'

ok so let's go installing zhudi-data.

$ sudo cp -R zhudi-data /usr/share/

$ zhudi -p pinyin -tr translation -sd simplified 
No config file found. Use defaults
Traceback (most recent call last):
  File "/usr/bin/zhudi_gui.py", line 5, in <module>
    pkg_resources.run_script('zhudi==1.4', 'zhudi_gui.py')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 483, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1348, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/zhudi-1.4-py2.7.egg/EGG-INFO/scripts/zhudi_gui.py", line 43, in <module>

  File "/usr/lib/python2.7/site-packages/zhudi-1.4-py2.7.egg/EGG-INFO/scripts/zhudi_gui.py", line 30, in main

  File "build/bdist.linux-x86_64/egg/zhudi/**init**.py", line 152, in prepare_data
UnboundLocalError: local variable 'simplified' referenced before assignment

**Comment by Jiehong** [comment]
Thanks for the report.

First, zhudi does not support python 2.7, so it should be done with python ≥ 3.1.
On the other hand, there is a problem with the splitting of the dictionary, and the launch later, and they look quite like you said.

Here is the first one.
$ zhudi -s cfdict.u8

```
Splitting dictionary in progress…
Traceback (most recent call last):
  File "/usr/bin/zhudi_gui.py", line 43, in <module>
    main()
  File "/usr/bin/zhudi_gui.py", line 30, in main
    dataObject, hanzi, romanisation, language = prepare_data(options)
  File "/usr/lib/python3.4/site-packages/zhudi/__init__.py", line 74, in prepare_data
    pinyin_list)
TypeError: __init__() missing 3 required positional arguments: 'cangjie5', 'cangjie5_short', and 'pinyin'
```

And the second one
$ zhudi -p pinyin -tr translation -sd simplified

```
No config file found. Use defaults
Traceback (most recent call last):
  File "/usr/bin/zhudi_gui.py", line 43, in <module>
     main()
  File "/usr/bin/zhudi_gui.py", line 30, in main
    dataObject, hanzi, romanisation, language = prepare_data(options)
  File "/usr/lib/python3.4/site-packages/zhudi/__init__.py", line 152, in prepare_data
    dataObject = data.Data(simplified, traditional, translation,
UnboundLocalError: local variable 'simplified' referenced before assignment
```

I'm sorry I didn't see that (I didn't update my dictionary file, so I didn't have to split it again).

I'll have a look so as to fix that.

**Comment by Jiehong** [comment]
I've fixed the first part in local.

The second part, actually, you need to pass all the arguments (so also traditional and zhuyin), and it works. I'll improve the error message.

**Comment by Jiehong** [comment]
You can now try again, and it should work correctly ;)

**Comment by pyluyten** [comment]
thanks.
I did update, then used python3 to install.

Dict split works now
$ zhudi -s cfdict.u8
Splitting dictionary in progress…
Warning: simplified has been moved to simplified_saved.
Indeed, this file will be created by Zhudi.
Warning: traditional has been moved to traditional_saved.
Indeed, this file will be created by Zhudi.
Warning: translation has been moved to translation_saved.
Indeed, this file will be created by Zhudi.
Warning: pinyin has been moved to pinyin_saved.
Indeed, this file will be created by Zhudi.

Pinyin to Zhuyin conversion in progress…
done.

And I can finally run the application - which looks pretty nice!

[buddho@localhost Zhudi]$ zhudi -p pinyin -tr translation -sd simplified
You must pass all generated files if launched manually
Try with:

```
-p pinyin -tr translation -sd simplified -z zhuyin -td traditional
```

[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ 
[buddho@localhost Zhudi]$ zhudi -p pinyin -tr translation -sd simplified -z zhuyin -td traditional
No config file found. Use defaults

**Comment by Jiehong** [comment]
Great :)
